Traceback (most recent call last):
  File "convnet_test.py", line 5, in <module>
    import lmdb
ImportError: No module named lmdb
